site_name: Brando Schema
site_description: Brando BDV is the world’s first Brand Definition Vocabulary for structuring brand identity, tone, and integrity in the AI Web.
site_author: Jonathan Bowker
site_url: https://brandoschema.com
repo_url: https://github.com/JonathanBowker/brandoschema.com
repo_name: GitHub

theme:
  name: "material"
  logo: "assets/images/logo.webp"
  palette:
    - scheme: "default"
      primary: "deep purple"
      accent: "indigo"
      toggle:
        icon: "material/weather-sunny"
        name: "Switch to dark mode"
    - scheme: "slate"
      primary: "indigo"
      accent: "indigo"
      toggle:
        icon: "material/weather-night"
        name: "Switch to light mode"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - "content.code.copy"
    - "header.autohide"
  icons:
    - material: true
    - fontawesome: true
    - octicons: true
  language: "en"

plugins:
  - search
  - tags
  - copy-well-known

extra:
  custom_domain: brandoschema.com
  meta:
    - name: keywords
      content: brando, brand definition language, bdl, brand schema, ai brand safety, structured branding, LLM prompts, AI web, semantic brand metadata, tone of voice schema
    - property: og:title
      content: Brando – The Brand Definition Language for the AI Web
    - property: og:description
      content: Brando is a machine-readable Brand Definition Language (BDL) that protects and structures brand identity in the AI era.
    - property: og:url
      content: https://brandoschema.com/bdl/
    - property: og:image
      content: https://brandoschema.com/assets/images/brando-og-image.png
    - name: twitter:card
      content: summary_large_image
    - name: twitter:title
      content: Brando – Brand Definition Language (BDL)
    - name: twitter:description
      content: Structure your brand identity, tone, and values for intelligent agents and LLMs with Brando BDL.
    - name: twitter:image
      content: https://brandoschema.com/assets/images/brando-og-image.png

extra_css:
  - "css/custom.css"

extra_javascript:
  - js/smooth-scroll.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.extra
  - md_in_html

nav:
  - Overview: index.md
  - Brando Classes: bdv-classes/index.md
  - Brando Terms: bdv-terms/index.md 
  - Using Brando: how-to-use.md
  - Licensing: licensing.md 
  - About: about.md
